version: '2'

services:
  eureka:
    build: ./eureka-server
    ports:
      - "8761:8761"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  pc:
    build: ./pc
    ports:
      - '8081:8080'
      - '5010:5005'
    depends_on:
      - eureka
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka/'

  po:
    build: ./po
    ports:
      - '8082:8080'
      - '5020:5005'
    links:
      - pc
    depends_on:
      - eureka
      - mongo
      - pc
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      pcurl: 'pc:8080'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka/'

  gateway:
    build: ./spring-cloud-gateway
    ports:
      - '8083:8080'
      - '5030:5005'
    links:
      - pc
    depends_on:
      - eureka
      - pc
    environment:
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      pcurl: 'http://pc:8080'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: 'http://eureka:8761/eureka/'

networks:
  default:
    driver: bridge
